from .test_search_building_code_view import SearchBuildingCodeViewTest
from .test_search_building_id_view import SearchBuildingIdViewTest
from .test_search_building_name_view import SearchBuildingNameViewTest
