from .test_garage_index_view import GarageSearchMapIndexViewTest
from .test_garage_map_view import GarageSearchMapViewTest
from .test_non_residential_index_view import NonResidentialSearchMapIndexViewTest
from .test_non_residential_map_view import NonResidentialSearchMapViewTest
from .test_residential_index_view import ResidentialSearchMapIndexViewTest
from .test_residential_map_view import ResidentialSearchMapViewTest
